### ISSUE TITLE
Does this language have a license?

### ISSUE THREAD

**Issue by Immortalin** [kevinlawler/kerf#10]

**Comment by kevinlawler** [comment]
I have no plans to open-source it or make it available for free. If someone wants to buy the IP, they can do what they wish with it.

**Comment by kevinlawler** [comment]
That's an interesting idea

**Comment by femtotrader** [comment]
http://www.timestored.com/b/open-source-kdb/ was an interesting article about idea of open sourcing kdb+ unfortunately it didn't occured.
kdb+ have Julia support thanks to https://github.com/enlnt/Q.jl ... open sourcing kerf could help to produce similar library... but I'm not specialist of timeseries database and still have some difficulties to understand differences between kerf, kona and kdb+

**Comment by femtotrader** [comment]
Maybe you should have a look at https://medium.com/open-collective/ten-steps-to-successful-open-source-crowdfunding-fa2b43e82687 and http://www.techdrivein.com/2012/12/top-5-kickstarter-crowdfunding-alternatives-opensource-software.html (maybe a bit outdated)

**Comment by kevinlawler** [comment]
Kerf1 source has been released under BSD-2-Clause

https://github.com/kevinlawler/kerf1/commit/84e47c0ffe0c247e8355e73cdaefd001ed9e9c73#diff-2c647d6a8baa61d721d2ebb8cd9cd112b903bdd8840baf666a9ec219a9da7a26

**Comment by femtotrader** [comment]
Thanks @kevinlawler

**Comment by ryanhamilton** [comment]
Very excited to see this Kevin. 👍 
More people in the world would benefit from exposure to the concepts in Kerf/APL/q.
