### ISSUE TITLE
int() of string/mixed vector produces spurious results

### ISSUE THREAD

**Issue by JohnEarnest** [kevinlawler/kerf#7]
KeRF> int ["1337", "43", "ABC"]
      [-2600464380, 4413724672, NAN, 1337, 43, 0]

    KeRF> int([5, "1337"])
      [5, 5, 5, 1337]

    KeRF> int([5.5, "1337"])
      [4617878467915022336, 4617878467915022336, 5, 1337]

edit: whoops, wrong repo. :s

**Comment by kevinlawler** [comment]
fixed in source
